export const springfieldAdress = [
    { number: 5202, street: 'Heming Ave' },
    { number: 7419, street: 'Gresham St' },
    { number: 7304, street: 'Elgar St' },
    { number: 5212, street: 'Ferndale St' },
    { number: 7506, street: 'Hogarth St' },
    { number: 7516, street: 'Hogarth St' },
    { number: 5301, street: 'Heming Ave' },
    { number: 1525, street: 'Q St NW' },
    { number: 5209, street: 'Kipling St' },
    { number: 1212, street: '30th St NW' },
    { number: 7608, street: 'Jervis St' },
    { number: 1225, street: '13th St NW APT 1020' },
    { number: 7225, street: 'Braddock Rd' },
    { number: 1718, street: 'P St NW # T6' },
    { number: 7220, street: 'Hansford Ct' },
    { number: 7113, street: 'Granberry Way' },
    { number: 7127, street: 'Woodland Dr' },
    { number: 7410, street: 'Gresham St' },
    { number: 7014, street: 'Woodland Dr' },
    { number: 7006, street: 'Leesville Blvd' },
    { number: 7014, street: 'Appomattox Ct' },
    { number: 5539, street: 'Belfast Pl' },
    { number: 7104, street: 'Granberry Way' },
    { number: 5216, street: 'Garner St' },
    { number: 7101, street: 'Catlett St' },
    { number: 7108, street: 'Leesville Blvd' },
    { number: 5222, street: 'Garner St' },
    { number: 7211, street: 'Leesville Blvd' },
    { number: 7209, street: 'Catlett St' },
    { number: 7202, street: 'Catlett St' },
    { number: 7315, street: 'Braddock Rd' },
    { number: 7320, street: 'Hansford Ct' },
    { number: 7333, street: 'Woodland Dr' },
    { number: 7347, street: 'Gresham St' },
    { number: 7359, street: 'Hogarth St' },
    { number: 7365, street: 'Ferndale St' },
    { number: 7378, street: 'Elgar St' },
    { number: 7382, street: 'Heming Ave' },
    { number: 7399, street: 'Q St NW' },
    { number: 7404, street: '13th St NW' },
    { number: 7417, street: '30th St NW' },
    { number: 7425, street: 'Belfast Pl' },
    { number: 7433, street: 'Kipling St' },
    { number: 7441, street: 'Garner St' },
    { number: 7456, street: 'Leesville Blvd' },
    { number: 7462, street: 'Appomattox Ct' },
    { number: 7475, street: 'Granberry Way' },
    { number: 7483, street: 'Hansford Ct' },
    { number: 7490, street: 'Cattlett St' },
    { number: 7502, street: 'Braddock Rd' },
    { number: 7514, street: 'P St NW' },
    { number: 7528, street: 'Jervis St' },
    { number: 7536, street: 'Woodland Dr' },
    { number: 7549, street: 'Hogarth St' },
    { number: 7555, street: 'Gresham St' },
    { number: 7567, street: 'Ferndale St' },
    { number: 7573, street: 'Elgar St' },
    { number: 7588, street: 'Heming Ave' }
];

  
export const baltimoreAdress = [
    { number: 2003, street: 'E North Ave' },
    { number: 1827, street: 'N Washington St' },
    { number: 1823, street: 'N Chapel St' },
    { number: 1723, street: 'N Durham St' },
    { number: 1707, street: 'E Lanvale St' },
    { number: 1625, street: 'N Broadway' },
    { number: 1627, street: 'E Lafayette Ave' },
    { number: 1745, street: 'N Bond St' },
    { number: 1332, street: 'Aisquith St' },
    { number: 538, street: 'E Preston St' },
    { number: 1115, street: 'Hunter St' },
    { number: 932, street: 'N Charles St' },
    { number: 8, street: 'W Read St' },
    { number: 303, street: 'Scott St' },
    { number: 770, street: 'Washington Blvd' },
    { number: 1631, street: 'Clarkson St' },
    { number: 8, street: 'W Heath St' },
    { number: 1706, street: 'Charles St' },
    { number: 3, street: 'E Heath St' },
    { number: 1726, street: 'Patapsco St' },
    { number: 45, street: 'E Barney St' },
    { number: 1815, street: 'Marshall St' },
    { number: 1833, street: 'Light St' },
    { number: 1541, street: 'Covington St' },
    { number: 1611, street: 'Belt St' },
    { number: 1620, street: 'Webster St' },
    { number: 900, street: 'E Fort Ave Garage' },
    { number: 1439, street: 'Lowman St' },
    { number: 1420, street: 'Decatur St' },
    { number: 1415, street: 'Cooksie St' },
    { number: 1502, street: 'E North Ave' },
    { number: 1754, street: 'N Washington St' },
    { number: 1802, street: 'N Chapel St' },
    { number: 1698, street: 'N Durham St' },
    { number: 1710, street: 'E Lanvale St' },
    { number: 1604, street: 'N Broadway' },
    { number: 1619, street: 'E Lafayette Ave' },
    { number: 1732, street: 'N Bond St' },
    { number: 1345, street: 'Aisquith St' },
    { number: 545, street: 'E Preston St' },
    { number: 1107, street: 'Hunter St' },
    { number: 940, street: 'N Charles St' },
    { number: 12, street: 'W Read St' },
    { number: 310, street: 'Scott St' },
    { number: 780, street: 'Washington Blvd' },
    { number: 1640, street: 'Clarkson St' },
    { number: 10, street: 'W Heath St' },
    { number: 1712, street: 'Charles St' },
    { number: 5, street: 'E Heath St' },
    { number: 1730, street: 'Patapsco St' },
    { number: 50, street: 'E Barney St' },
    { number: 1820, street: 'Marshall St' },
    { number: 1840, street: 'Light St' },
    { number: 1550, street: 'Covington St' },
    { number: 1622, street: 'Belt St' },
    { number: 1630, street: 'Webster St' },
    { number: 905, street: 'E Fort Ave Garage' },
    { number: 1445, street: 'Lowman St' },
    { number: 1430, street: 'Decatur St' },
    { number: 1420, street: 'Cooksie St' }
];


export const orlandoAdress = [
    { number: 1615, street: "Briarcliff Dr" },
    { number: 1812, street: "Curry Ford Rd" },
    { number: 2125, street: "Henderson Dr" },
    { number: 2418, street: "Carlton Dr" },
    { number: 9111, street: "Lake Margaret Dr" },
    { number: 3127, street: "Heathgate Ct" },
    { number: 4304, street: "Inwood Landing Dr" },
    { number: 1658, street: "Buckeye Falls Way" },
    { number: 1923, street: "Canoe Creek Falls Dr" },
    { number: 1819, street: "Canoe Creek Falls Dr" },
    { number: 6748, street: "Oman Ct" },
    { number: 6736, street: "Oman Ct" },
    { number: 6697, street: "Rivo Alto Ave" },
    { number: 6660, street: "Broadmoor Dr" },
    { number: 811, street: "Jordan Ave" },
    { number: 725, street: "Forester Ave" },
    { number: 6823, street: "Bouganville Crescent Dr" },
    { number: 6745, street: "Bouganville Crescent Dr" },
    { number: 595, street: "Conure St" },
    { number: 529, street: "Conure St" },
    { number: 556, street: "Sparrow Ct" },
    { number: 565, street: "Martin Pl Blvd" },
    { number: 458, street: "Breezeway Dr" },
    { number: 343, street: "Lookout Ln" },
    { number: 318, street: "Bluff Ln" },
    { number: 770, street: "Ashworth Overlook Dr" },
    { number: 549, street: "Breezy Oak Way" },
    { number: 534, street: "Jasmine Bloom Dr" },
    { number: 1132, street: "Magnolia Blossom Ct" },
    { number: 1543, street: "Lawson Palm Ct" },
    { number: 1441, street: "Madison Ivy Cir" },
    { number: 2351, street: "Harbor Point Blvd" },
    { number: 1207, street: "Summerlin Ave" },
    { number: 892, street: "Goldenrod Rd" },
    { number: 650, street: "Fairway Cove Dr" },
    { number: 745, street: "Oak Manor Cir" },
    { number: 1833, street: "Pershing Ave" },
    { number: 2724, street: "Wilmington Cir" },
    { number: 3045, street: "Dolphin Ave" },
    { number: 3982, street: "Sandlake Rd" },
    { number: 521, street: "Holly Hill Dr" },
    { number: 1081, street: "Palm Creek Ave" },
    { number: 1905, street: "Willow Bend Blvd" },
    { number: 1502, street: "Ferncreek Ave" },
    { number: 832, street: "Cypress Springs Pkwy" },
    { number: 2789, street: "Lake Baldwin Ln" },
    { number: 3741, street: "Crystal Bay Ln" },
    { number: 2254, street: "Vista Oaks Dr" },
    { number: 1895, street: "Park Center Dr" },
    { number: 3306, street: "Silver Star Rd" },
    { number: 4405, street: "Sunbeam Ln" },
    { number: 1292, street: "Tanglewood St" },
    { number: 3148, street: "Sunset Blvd" },
    { number: 2501, street: "Brandywine Dr" },
    { number: 5213, street: "Cedar Ridge Dr" },
    { number: 3759, street: "Golden Lake Dr" },
    { number: 2804, street: "Edgewater Dr" },
    { number: 4900, street: "Sagebrush St" },
    { number: 3820, street: "Lakeshore Dr" }
];