const springfield = [
  { name: 'Alexandria', id: 1 },
  { name: 'Arlington', id: 2 },
  { name: 'Annandale', id: 3 },
  { name: 'Bethesda', id: 4 },
  { name: 'Bowie', id: 5 },
  { name: 'Brians Road', id: 6 },
  { name: 'Burke', id: 7 },
  { name: 'Capitol Heights', id: 8 },
  { name: 'Chevy Chase', id: 9 },
  { name: 'Clinton', id: 10 },
  { name: 'Dumfries', id: 11 },
  { name: 'District Heights', id: 12 },
  { name: 'Falls Church', id: 13 },
  { name: 'Falls Church', id: 14 },
  { name: 'Fairfax', id: 15 },
  { name: 'Fairfax Station', id: 16 },
  { name: 'Fort Washington', id: 17 },
  { name: 'Germantown', id: 18 },
  { name: 'Gaitersburg', id: 19 },
  { name: 'Great Falls', id: 20 },
  { name: 'Hyattsville', id: 21 },
  { name: 'Kensington', id: 22 },
  { name: 'Landover', id: 23 },
  { name: 'Lorton', id: 24 },
  { name: 'Manassas', id: 25 },
  { name: 'McLean', id: 26 },
  { name: 'MC Lean', id: 27 },
  { name: 'Oxon Hill', id: 28 },
  { name: 'Potomac', id: 29 },
  { name: 'Poolesville', id: 30 },
  { name: 'Rockville', id: 31 },
  { name: 'Silver Spring', id: 32 },
  { name: 'Springfield', id: 33 },
  { name: 'Suitland', id: 34 },
  { name: 'Temple Hills', id: 35 },
  { name: 'Upper Marlboro', id: 36 },
  { name: 'Vienna', id: 37 },
  { name: 'Woodbridge', id: 38 },
  { name: 'Washington', id: 39 },
];

const elkrigde = [
  { name: 'Annapolis', id: 1 },
  { name: 'Baltimore', id: 2 },
  { name: 'Beltsville', id: 3 },
  { name: 'Bowie', id: 4 },
  { name: 'Boyds', id: 5 },
  { name: 'Catonsville', id: 6 },
  { name: 'Chillum', id: 7 },
  { name: 'Collesville', id: 8 },
  { name: 'Columbia', id: 9 },
  { name: 'Damascus', id: 10 },
  { name: 'Davidsonville', id: 11 },
  { name: 'Dundalk', id: 12 },
  { name: 'Edgewater', id: 13 },
  { name: 'Edgemere', id: 14 },
  { name: 'Edgewood', id: 15 },
  { name: 'Elkridge', id: 16 },
  { name: 'Ellicott City', id: 17 },
  { name: 'Essex', id: 18 },
  { name: 'Finksburg', id: 19 },
  { name: 'Frederick', id: 20 },
  { name: 'Gaithersburg', id: 21 },
  { name: 'Germantown', id: 22 },
  { name: 'Glen Burnie', id: 23 },
  { name: 'Glenarden', id: 24 },
  { name: 'Greenbelt', id: 25 },
  { name: 'Hanover', id: 26 },
  { name: 'Hyattsville', id: 27 },
  { name: 'Ijamsville', id: 28 },
  { name: 'Laurel', id: 29 },
  { name: 'Lanham', id: 30 },
  { name: 'Lutherville', id: 31 },
  { name: 'Middle River', id: 32 },
  { name: 'Middletown', id: 33 },
  { name: 'Mitcheville', id: 34 },
  { name: 'Montgomery Village', id: 35 },
  { name: 'Mount Airy', id: 36 },
  { name: 'New Carrollton', id: 37 },
  { name: 'Olney', id: 38 },
  { name: 'Owings Mill', id: 39 },
  { name: 'Parksville', id: 40 },
  { name: 'Passadena', id: 41 },
  { name: 'Poolesville', id: 42 },
  { name: 'Reisterstown', id: 43 },
  { name: 'Riva', id: 44 },
  { name: 'Randalstown', id: 45 },
  { name: 'Riverdale', id: 46 },
  { name: 'Rockville', id: 47 },
  { name: 'Rosedale', id: 48 },
  { name: 'Silver Spring', id: 49 },
  { name: 'Sparrows Point', id: 50 },
  { name: 'Springdale', id: 51 },
  { name: 'Takoma Park', id: 52 },
  { name: 'Timonium', id: 53 },
  { name: 'Urbana', id: 54 },
  { name: 'Upperco', id: 55 },
  { name: 'Westminster', id: 56 },
  { name: 'White Marsh', id: 57 },
  { name: 'Woodbine', id: 58 },
];

const westborough = [
  { name: 'Acton', id: 1 },
  { name: 'Andover', id: 2 },
  { name: 'Arlington', id: 3 },
  { name: 'Ashland', id: 4 },
  { name: 'Bedford', id: 5 },
  { name: 'Belmont', id: 6 },
  { name: 'Beverly', id: 7 },
  { name: 'Billerica', id: 8 },
  { name: 'Boston', id: 9 },
  { name: 'Braintree', id: 10 },
  { name: 'Brookline', id: 11 },
  { name: 'Burlington', id: 12 },
  { name: 'Cambridge', id: 13 },
  { name: 'Canton', id: 14 },
  { name: 'Carlisle', id: 15 },
  { name: 'Chelmsford', id: 16 },
  { name: 'Chelsea', id: 17 },
  { name: 'Concord', id: 18 },
  { name: 'Danvers', id: 19 },
  { name: 'Dedham', id: 20 },
  { name: 'Dover', id: 21 },
  { name: 'Everett', id: 22 },
  { name: 'Framingham', id: 23 },
  { name: 'Franklin', id: 24 },
  { name: 'Gloucester', id: 25 },
  { name: 'Groveland', id: 26 },
  { name: 'Hingham', id: 27 },
  { name: 'Holbrook', id: 28 },
  { name: 'Holliston', id: 29 },
  { name: 'Hopkinton', id: 30 },
  { name: 'Hudson', id: 31 },
  { name: 'Lexington', id: 32 },
  { name: 'Lincoln', id: 33 },
  { name: 'Lynn', id: 34 },
  { name: 'Lynnfield', id: 35 },
  { name: 'Malden', id: 36 },
  { name: 'Manchester-by-the-Sea', id: 37 },
  { name: 'Marblehead', id: 38 },
  { name: 'Marlborough', id: 39 },
  { name: 'Maynard', id: 40 },
  { name: 'Medfield', id: 41 },
  { name: 'Medford', id: 42 },
  { name: 'Melrose', id: 43 },
  { name: 'Middleton', id: 44 },
  { name: 'Milford', id: 45 },
  { name: 'Millis', id: 46 },
  { name: 'Milton', id: 47 },
  { name: 'Natick', id: 48 },
  { name: 'Needham', id: 49 },
  { name: 'Newton', id: 50 },
  { name: 'North Reading', id: 51 },
  { name: 'Norwood', id: 52 },
  { name: 'Peabody', id: 53 },
  { name: 'Quincy', id: 54 },
  { name: 'Randolph', id: 55 },
  { name: 'Reading', id: 56 },
  { name: 'Revere', id: 57 },
  { name: 'Rockport', id: 58 },
  { name: 'Salem', id: 59 },
  { name: 'Saugus', id: 60 },
  { name: 'Scituate', id: 61 },
  { name: 'Sharon', id: 62 },
  { name: 'Sherborn', id: 63 },
  { name: 'Somerville', id: 64 },
  { name: 'Stoneham', id: 65 },
  { name: 'Stoughton', id: 66 },
  { name: 'Sudbury', id: 67 },
  { name: 'Swampscott', id: 68 },
  { name: 'Tewksbury', id: 69 },
  { name: 'Topsfield', id: 70 },
  { name: 'Wakefield', id: 71 },
  { name: 'Walpole', id: 72 },
  { name: 'Waltham', id: 73 },
  { name: 'Watertown', id: 74 },
  { name: 'Wayland', id: 75 },
  { name: 'Wellesley', id: 76 },
  { name: 'West Roxbury', id: 77 },
  { name: 'Westborough', id: 78 },
  { name: 'Westford', id: 79 },
  { name: 'Weston', id: 80 },
  { name: 'Westwood', id: 81 },
  { name: 'Weymouth', id: 82 },
  { name: 'Winchester', id: 83 },
  { name: 'Winthrop', id: 84 },
  { name: 'Woburn', id: 85 },
];

const orlando = [
  { name: 'Altamonte Springs', id: 1 },
  { name: 'Apopka', id: 2 },
  { name: 'Belle Isle', id: 3 },
  { name: 'Bithlo', id: 4 },
  { name: 'Casselberry', id: 5 },
  { name: 'Clermont', id: 6 },
  { name: 'Conway', id: 7 },
  { name: 'Doctor Phillips', id: 8 },
  { name: 'Edgewood', id: 9 },
  { name: 'Eustis', id: 10 },
  { name: 'Geneva', id: 11 },
  { name: 'Howey-in-the-Hills', id: 12 },
  { name: 'Kissimmee', id: 13 },
  { name: 'Lake Buena Vista', id: 14 },
  { name: 'Lake Mary', id: 15 },
  { name: 'Longwood', id: 16 },
  { name: 'Maitland', id: 17 },
  { name: 'Mount Dora', id: 18 },
  { name: 'Oakland', id: 19 },
  { name: 'Ocoee', id: 20 },
  { name: 'Orlando', id: 21 },
  { name: 'Oviedo', id: 22 },
  { name: 'Pine Hills', id: 23 },
  { name: 'Poinciana', id: 24 },
  { name: 'Sanford', id: 25 },
  { name: 'St. Cloud', id: 26 },
  { name: 'Tavares', id: 27 },
  { name: 'The Villages', id: 28 },
  { name: 'Wedgefield', id: 29 },
  { name: 'Windermere', id: 30 },
  { name: 'Winter Garden', id: 31 },
  { name: 'Winter Park', id: 32 },
  { name: 'Winter Springs', id: 33 },
];


const city = [
  { name: 'Springfield', id: 1 },
  { name: 'Elkridge', id: 2 },
  { name: 'Baltimore', id: 3 },
  { name: 'Westborough', id: 4 },
  { name: 'Orlando', id: 5 },
];

export { springfield, elkrigde, city, westborough, orlando };

// Caso a cidade de saida tenha o id menor ou igual a 38, a cidade picked up será Springfield, caso contrário, a cidade picked up será Elkridge

// Picked up antes das 04:00 = vencimento até as 08:00
// Picked up entre as 04:00 e 07:00 = vencimento até as 11:00
// Picked up entre as 11:00 e 13:00 = vencimento até as 18:00
// Picked up após as 13:00 = vencimento até as 22:00
