export const stations = [
  {
    id: 1,
    name: 'Springfield',
    cities: [
      { name: 'Alexandria'},
      { name: 'Arlington'},
      { name: 'Annandale'},
      { name: 'Bethesda'},
      { name: 'Bowie'},
      { name: 'Brians Road'},
      { name: 'Burke'},
      { name: 'Capitol Heights'},
      { name: 'Chevy Chase'},
      { name: 'Clinton'},
      { name: 'Dumfries'},
      { name: 'District Heights'},
      { name: 'Falls Church'},
      { name: 'Falls Church'},
      { name: 'Fairfax'},
      { name: 'Fairfax Station'},
      { name: 'Fort Washington'},
      { name: 'Germantown'},
      { name: 'Gaitersburg'},
      { name: 'Great Falls'},
      { name: 'Hyattsville'},
      { name: 'Kensington'},
      { name: 'Landover'},
      { name: 'Lorton'},
      { name: 'Manassas'},
      { name: 'McLean'},
      { name: 'MC Lean'},
      { name: 'Oxon Hill'},
      { name: 'Potomac'},
      { name: 'Poolesville'},
      { name: 'Rockville'},
      { name: 'Silver Spring'},
      { name: 'Springfield'},
      { name: 'Suitland'},
      { name: 'Temple Hills'},
      { name: 'Upper Marlboro'},
      { name: 'Vienna'},
      { name: 'Woodbridge'},
      { name: 'Washington'},
    ]
  },
  {
    id: 2,
    name: 'Elkridge',
    cities: [
      { name: 'Annapolis'},
      { name: 'Baltimore'},
      { name: 'Beltsville'},
      { name: 'Bowie'},
      { name: 'Boyds'},
      { name: 'Catonsville'},
      { name: 'Chillum'},
      { name: 'Collesville'},
      { name: 'Columbia'},
      { name: 'Damascus'},
      { name: 'Davidsonville'},
      { name: 'Dundalk'},
      { name: 'Edgewater'},
      { name: 'Edgemere'},
      { name: 'Edgewood'},
      { name: 'Elkridge'},
      { name: 'Ellicott City'},
      { name: 'Essex'},
      { name: 'Finksburg'},
      { name: 'Frederick'},
      { name: 'Gaithersburg'},
      { name: 'Germantown'},
      { name: 'Glen Burnie'},
      { name: 'Glenarden'},
      { name: 'Greenbelt'},
      { name: 'Hanover'},
      { name: 'Hyattsville'},
      { name: 'Ijamsville'},
      { name: 'Laurel'},
      { name: 'Lanham'},
      { name: 'Lutherville'},
      { name: 'Middle River'},
      { name: 'Middletown'},
      { name: 'Mitcheville'},
      { name: 'Montgomery Village'},
      { name: 'Mount Airy'},
      { name: 'New Carrollton'},
      { name: 'Olney'},
      { name: 'Owings Mill'},
      { name: 'Parksville'},
      { name: 'Passadena'},
      { name: 'Poolesville'},
      { name: 'Reisterstown'},
      { name: 'Riva'},
      { name: 'Randalstown'},
      { name: 'Riverdale'},
      { name: 'Rockville'},
      { name: 'Rosedale'},
      { name: 'Silver Spring'},
      { name: 'Sparrows Point'},
      { name: 'Springdale'},
      { name: 'Takoma Park'},
      { name: 'Timonium'},
      { name: 'Urbana'},
      { name: 'Upperco'},
      { name: 'Westminster'},
      { name: 'White Marsh'},
      { name: 'Woodbine'},
    ]
  },
  {
    id: 3,
    name: 'Baltimore',
    cities: [
      { name: 'Annapolis'},
      { name: 'Baltimore'},
      { name: 'Beltsville'},
      { name: 'Bowie'},
      { name: 'Boyds'},
      { name: 'Catonsville'},
      { name: 'Chillum'},
      { name: 'Collesville'},
      { name: 'Columbia'},
      { name: 'Damascus'},
      { name: 'Davidsonville'},
      { name: 'Dundalk'},
      { name: 'Edgewater'},
      { name: 'Edgemere'},
      { name: 'Edgewood'},
      { name: 'Elkridge'},
      { name: 'Ellicott City'},
      { name: 'Essex'},
      { name: 'Finksburg'},
      { name: 'Frederick'},
      { name: 'Gaithersburg'},
      { name: 'Germantown'},
      { name: 'Glen Burnie'},
      { name: 'Glenarden'},
      { name: 'Greenbelt'},
      { name: 'Hanover'},
      { name: 'Hyattsville'},
      { name: 'Ijamsville'},
      { name: 'Laurel'},
      { name: 'Lanham'},
      { name: 'Lutherville'},
      { name: 'Middle River'},
      { name: 'Middletown'},
      { name: 'Mitcheville'},
      { name: 'Montgomery Village'},
      { name: 'Mount Airy'},
      { name: 'New Carrollton'},
      { name: 'Olney'},
      { name: 'Owings Mill'},
      { name: 'Parksville'},
      { name: 'Passadena'},
      { name: 'Poolesville'},
      { name: 'Reisterstown'},
      { name: 'Riva'},
      { name: 'Randalstown'},
      { name: 'Riverdale'},
      { name: 'Rockville'},
      { name: 'Rosedale'},
      { name: 'Silver Spring'},
      { name: 'Sparrows Point'},
      { name: 'Springdale'},
      { name: 'Takoma Park'},
      { name: 'Timonium'},
      { name: 'Urbana'},
      { name: 'Upperco'},
      { name: 'Westminster'},
      { name: 'White Marsh'},
      { name: 'Woodbine'},
    ]
  },
  {
    id: 4,
    name: 'Westborough',
    cities: [
      { name: 'Acton'},
      { name: 'Andover'},
      { name: 'Arlington'},
      { name: 'Ashland'},
      { name: 'Bedford'},
      { name: 'Belmont'},
      { name: 'Beverly'},
      { name: 'Billerica'},
      { name: 'Boston'},
      { name: 'Braintree'},
      { name: 'Brookline'},
      { name: 'Burlington'},
      { name: 'Cambridge'},
      { name: 'Canton'},
      { name: 'Carlisle'},
      { name: 'Chelmsford'},
      { name: 'Chelsea',},
      { name: 'Concord'},
      { name: 'Danvers'},
      { name: 'Dedham'},
      { name: 'Dover'},
      { name: 'Everett'},
      { name: 'Framingham'},
      { name: 'Franklin'},
      { name: 'Gloucester'},
      { name: 'Groveland'},
      { name: 'Hingham'},
      { name: 'Holbrook'},
      { name: 'Holliston'},
      { name: 'Hopkinton'},
      { name: 'Hudson'},
      { name: 'Lexington'},
      { name: 'Lincoln'},
      { name: 'Lynn'},
      { name: 'Lynnfield'},
      { name: 'Malden'},
      { name: 'Manchester-by-the-Sea'},
      { name: 'Marblehead'},
      { name: 'Marlborough'},
      { name: 'Maynard'},
      { name: 'Medfield'},
      { name: 'Medford'},
      { name: 'Melrose'},
      { name: 'Middleton'},
      { name: 'Milford'},
      { name: 'Millis'},
      { name: 'Milton'},
      { name: 'Natick'},
      { name: 'Needham'},
      { name: 'Newton'},
      { name: 'North Reading'},
      { name: 'Norwood'},
      { name: 'Peabody'},
      { name: 'Quincy'},
      { name: 'Randolph'},
      { name: 'Reading'},
      { name: 'Revere'},
      { name: 'Rockport'},
      { name: 'Salem'},
      { name: 'Saugus'},
      { name: 'Scituate'},
      { name: 'Sharon'},
      { name: 'Sherborn'},
      { name: 'Somerville'},
      { name: 'Stoneham'},
      { name: 'Stoughton'},
      { name: 'Sudbury',},
      { name: 'Swampscott',},
      { name: 'Tewksbury'},
      { name: 'Topsfield'},
      { name: 'Wakefield'},
      { name: 'Walpole'},
      { name: 'Waltham'},
      { name: 'Watertown' },
      { name: 'Wayland'},
      { name: 'Wellesley'},
      { name: 'West Roxbury'},
      { name: 'Westborough'},
      { name: 'Westford'},
      { name: 'Weston'},
      { name: 'Westwood'},
      { name: 'Weymouth'},
      { name: 'Winchester'},
      { name: 'Winthrop'},
      { name: 'Woburn'},
    ]
  },
  {
    id: 5,
    name: 'Orlando',
    cities: [
      { name: 'Altamonte Springs'},
      { name: 'Apopka'},
      { name: 'Belle Isle'},
      { name: 'Bithlo'},
      { name: 'Casselberry'},
      { name: 'Clermont'},
      { name: 'Conway'},
      { name: 'Doctor Phillips'},
      { name: 'Edgewood'},
      { name: 'Eustis'},
      { name: 'Geneva'},
      { name: 'Howey-in-the-Hills'},
      { name: 'Kissimmee'},
      { name: 'Lake Buena Vista'},
      { name: 'Lake Mary'},
      { name: 'Longwood'},
      { name: 'Maitland'},
      { name: 'Mount Dora'},
      { name: 'Oakland'},
      { name: 'Ocoee'},
      { name: 'Orlando'},
      { name: 'Oviedo'},
      { name: 'Pine Hills'},
      { name: 'Poinciana'},
      { name: 'Sanford'},
      { name: 'St. Cloud'},
      { name: 'Tavares'},
      { name: 'The Villages'},
      { name: 'Wedgefield'},
      { name: 'Windermere'},
      { name: 'Winter Garden'},
      { name: 'Winter Park'},
      { name: 'Winter Springs'},
    ]
  },
]

export const packageNumbers = [
  'L01', 'L02', 'L03', 'L04', 'L05', 'L06', 'L07', 'L08', 'L09', 'L10',
  'L11', 'L12', 'L13', 'L14', 'L15', 'L16', 'L17', 'L18', 'L19', 'L20',
  'L21', 'L22', 'L23', 'L24', 'L25', 'L26', 'L27', 'L28', 'L29', 'L30',
  'L31', 'L32', 'L33', 'L34', 'L35', 'L36', 'L37', 'L38', 'L39', 'L40',
];

export const PackageQuantities = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
  28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
];

export const letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'];